### ISSUE TITLE
[Bug] DoE lavamen in R2M3

### ISSUE THREAD

**Issue by NightFright2k19** [Shpoike/Quakespasm#26]
In DoE's R2M3 "Elemental Fury II", lavamen #2-4 do not spawn in their lava pools, but on the floor/level below. Additionally, they won't stay put (as they should), but roam around freely and chase the player. They can still be killed to reveal the switches. Cannot be fixed by setting "sv_gameplayfix_setmodelrealbox 0". First lavaman spawns and behaves correctly.

Suspicion: droptofloor () from lavaman.qc (in void() lavaman_awake) might not work as intended when models are spawning in these suspended lava pools.

Problem does not occur in official Quakespasm v0.93.2 x64 (from 2019-11-12).

**Comment by adelpha** [comment]
As a test, I just shifted the broken lavamen +16 on the z axis. It fixed 2 of them, but the final one needed 20 units to stop falling through.

"origin" "-888 -64 **132**" to "origin" "-888 -64 **148**" (+16)

"origin" "-880 64 **348**" to "origin" "-880 64 **364**" (+16)

"origin" "-200 -64 **372**" to "origin" "-200 -64 **392**" (+20)

So they're either spawning too low to begin with (unlikely, i guess), or as you say, droptofloor isn't testing as it did in the past.

**Comment by NightFright2k19** [comment]
droptofloor() is not exactly the correct syntax, anyway. Should be droptofloor(0,0). Anyway, I also tried a fixed progs.dat with that and it didn't make any difference. 
It worked in vanilla, so I dunno why QSS has problems with it. Anyway, you can provide an external .ent file to fix that issue if you don't want to place an exception case for that map in the code.

**Comment by adelpha** [comment]
Thing is, QSS _shouldn't be_ different from QS or WQ in this behaviour. There are probably other maps out there with similar setups that are also affected, so the fix should be in the engine and not special-cased.

**Comment by NightFright2k19** [comment]
My wildest guess, without having any idea about anything, is that for some reason QSS doesn't recognize the pool floor for lavamen no. 3+4 because they are clipping into it. In other ports, it thinks "OK, if it's clipping into a brush, I am moving the model up to the next higher floor" and here it's like "Fine, then it's dropping to the lower floor". Again, that's what it looks like to me, it can be something else entirely.

**Comment by adelpha** [comment]
Just as an aside, vkQuake has also inherited this problem - although only the last lavaman falls through in vkQuake, instead of 3 of them.

QS 0.93.2 remains unaffected.

**Comment by Shpoike** [comment]
QS's tracebox was rewritten to a) be faster b) be more precise.
That precision improvement is what fixes the weird collisions you might have in QS which sometimes prevent you from crossing into more open rooms (vanilla/QS will often find a solid leaf to the side instead of the leaf it SHOULD be crossing into).

Unfortunately it has a slightly different behaviour for trace_allsolid. QSS will see the cavity below and report allsolid while QS will somehow treat allsolid as more like startsolid. The droptofloor builtin checks allsolid (for some reason) rather than startsolid, and QSS will then use that cavity that it found (the start might be solid, but the final impact point is empty).

To be clear, those lavamen really are positioned inside walls, and the qc code doesn't bother warning about it. On the plus side, I suppose this also stops them from moving out of their rather small lava pits.

**Comment by Shpoike** [comment]
fixed by https://github.com/Shpoike/Quakespasm/commit/c6ecb243d66868b776440258468ce03e9b768ef7
