### ISSUE TITLE
[Feature Request] Add QSS/Arcane Dimension particle system toggle to the menu

### ISSUE THREAD

**Issue by BreakPoints** [Shpoike/Quakespasm#51]
A toggle in the menu to allow for AD maps to fall back to the classic Quake particle system only for those who want to play these maps without the new particles.

(Follow-up: an option to choose Nearest Neighbour or Bilinear texture filtering on the QSS particle system would also be appreciated, to better fit unfiltered map textures)

**Comment by Shpoike** [comment]
I understand the sentiment, but whether a mod uses various QC extensions or not is a choice for the mod, not the engine.
Allowing users to (easily) block arbitrary extensions is a great way to encourage users to break mods that depend upon those features.

Ultimately AD has a lot of its own settings/binds/etc which should probably be configured via a mod-defined menu(read: CSQC or MenuQC) rather than adding mod-specific hacks to the engine. Ultimately anything that FULLY disables AD's various types of particles HAS to be mod specific due to its fallback of using sprites.
