### ISSUE TITLE
[Severe Bug] Wrong enemy/item spawns in various maps

### ISSUE THREAD

**Issue by NightFright2k19** [Shpoike/Quakespasm#80]
In HIP3M3 "Limbo", Vore spawns do not happen as intended when trying to grab the silver key from the rising platform. Two of them get stuck underneath their "spawn boxes" (non-player space) and never appear, creating a showstopper since you need to kill all enemies to make the platform with the key lower.

Works with: Quakespasm 0.94.1
Does not work with: Quakespasm-Spiked 2021-09-13 (x64)

General note: QSS reliability has apparently suffered during the latest updates. From Func_Msgboard there are reports about wrong monster/item placement throughout various maps, e.g.:
- E2M1 "The Installation": explosive box appearing on path across water area to gold key
- "Putrid Pumps": two Ogres stuck in floor
- "Slime Factory": three Knights not teleporting in for the final fight since they are stuck in the floor
- "Squire of Time": "Armored Nightmare" map has rocket boxes stuck in the ceiling
- "Cimmerian Night": First map has explosive box stuck in the ceiling
- "Into The Dark": three Shamblers stuck in floor, one Fiend falling through map, Lightning Gun + 2 cell boxes floating in the void

**Comment by NightFright2k19** [comment]
Looks like Oct 6 build improves things at least a bit. The HIP3M3 showstopper with spawns not happening seems to be gone. However, that wrong explosive box in E2M1 is still there, which makes me wonder which of the other problems mentioned above still exist.

**Comment by strangebit** [comment]
Regarding the E2M1 thing, I first noticed this a while back and mentioned it on the Authentic Model Improvements thread, because for me this happens only when using b_exbox2.bsp from Authentic Model Improvements and only on the remaster E2M1. So are you using AMI when you're encountering this too? Not saying it's AMI that is broken; I don't know what is the issue. Just want to mention this in case it helps in figuring it out.

**Comment by NightFright2k19** [comment]
You are right, I am using the Authentic Models, and the issue wouldn't happen without them. Yet in Quakespasm it would look fine, anyway. I even checked the Kex edition of E2M1, assuming they would have changed the position of the box slightly at least, but apparently that's not the case.

However, it seems that all the other spawn-related issues are fixed with the Oct 6 build, so this ticket can be considered solved.

**Comment by Shpoike** [comment]
significant differences in hull-based collisions are either due to either:

a) sv_gameplayfix_setmodelrealbox - QS's effective value of 1 leaves the sizes of mdls effectively random when people are using replacement content, resulting in entities getting pushed into the floors etc simply because the replacement was a slightly different size. So, with the exception of .bsp files any instances of these should be considered QC bugs. QSS now defaults this cvar to 0 to match vanilla behaviour which sidesteps most of this mess - so long as the mod was actually properly tested with vanilla. BSPs are the singular exception, with any replacements for said .bsp files being required to match the original model's bounds as closely as possible (*ESPECIALLY* the mins value), if there are further issues (eg with exploboxes) then you should stop using said replacement content.
QSS defaulting to 0 at least ensures more consistent behaviour, hopefully reducing the chances of it being an issue in the future. Fewer people reporting unreproduceable behaviour is always going to be a good thing, as is quakerally/etc working out of the box.

b) tracebox differences (aka pr_checkextension 0 for vanilla results). QSS's tracebox is intended to retain better precision avoiding glitches where doorways into rooms (or the top of ramps) could block your progress despite opening up. Its also meant to be more efficient too. The problem is that its different, as well as more predictable with its results when reporting trace_startsolid. This can cause issues. You can just disable extensions and revert to the vanilla QS behaviour now though, if it is actually a problem.
