### ISSUE TITLE
[Bug] Actual version of QSS and Operation: Urth Majik

### ISSUE THREAD

**Issue by GenericJohnDoeNO0** [Shpoike/Quakespasm#82]
Hi there!
When i try to launch "Operation: Urth Majik" with the actual Version of QSS all Text is garbled and unreadable. 
The text is there but the letters are wrong.

Older Versions from QSS will work (Git Revision: 3c5059a12d505be4942ea73e3745590270443476, Git Date: 2021-03-06, Compile Date: Sat, Mar 6, 06:43:10 UTC 2021) and the normal actual quakespasm will work, too.

I am too newbie to fix the problem in the map, maybe a fix here or a guideline how i can correct the text for qss in Operation: Urth Majik would help!

This is a picture of the console just after the startup:

![garbled text](https://user-images.githubusercontent.com/92174283/136590471-1cbe4102-efbf-4290-927f-a684b48b6eeb.jpg)

This is the same picture when the latest quakespasm engine is used:

![good text](https://user-images.githubusercontent.com/92174283/136590861-41ee24ae-53e3-4d0a-b0e9-7a551478ed7e.jpg)

Everything seems to had jumped to the next letter in the alphabeth and the next number.

**Comment by GenericJohnDoeNO0** [comment]
Deletion of the chonchars.lmp in the gfx folder of the pak0.pak of this mod fixes this behaviour. I do not know if this was a faulty file in the release version of the episode or if it is a bug in the current version of qss.

**Comment by NightFright2k19** [comment]
I am confirming this issue.

**Comment by Shpoike** [comment]
the image is actually a qpic image with its 8-byte header and everything, but its glyphs are misordered.
earlier versions interpretted the 8-byte header as part of the image itself and ignored the last 8 bytes of pixel data instead.
Whoever exported that wad just hacked around their tools instead of exporting it properly.
I believe I tweaked qss's behaviour a while back. you'll still get a warning about the size being wrong though.
