### ISSUE TITLE
Weird texture glitches

### ISSUE THREAD

**Issue by Lonsfor** [Shpoike/Quakespasm#83]
there are some strange texture glitches on the map [Punishment Due](https://www.quaddicted.com/reviews/pun.html)
![spasm0004](https://user-images.githubusercontent.com/15758649/136632012-9a1fb47a-6654-4f92-b106-846cca5533ce.png)

it looks normal on quakespasm
![spasm0005](https://user-images.githubusercontent.com/15758649/136632035-afcb0138-20af-41f4-8e95-91b749723f00.png)

this is on latest master

**Comment by NightFright2k19** [comment]
If this is "Azure Annoyance" (first map of the episode), it looks normal to me. Maybe better provide your system specs, especially your graphics card.

**Comment by Oplexitie** [comment]
Ok, so I've found a way to replicate this issue (I think), but in Scourge of Armagon. Turn on Vanilla Quake, and start a new game. Once inside the start map, load the hipnotic expansion via commands. Then inside the hipnotic menu, start a new game and normally you should get a flickering glitch button at the start, or something else, I had the entire menu glitched out once.

![spasm0000](https://user-images.githubusercontent.com/72892666/140634510-e2586b24-d09f-4964-b440-e99242946efe.jpg)

Anyways, I've only been able to trigger this bug when loading an expansion from within the game, loading the expansion via external commands (like Win10 cmd) doesn't seem to trigger the issue on my end.

To conclude, I can confirm that this is not a hardware issue, since I've triggered the bug on my desktop (Win10 with RTX) and my laptop (Linux Mint with integrated graphic card). Also, this bug seems to be unique to QSS since I couldn't replicate it in Quakespasm 0.94.2 . FYI I used the October 14 QSS build.

**Comment by adelpha** [comment]
Confirmed. Can replicate same as Oplexitie.

1. Load QSS.
2. Start a new game.
3. In start map do "game hipnotic" in console.
4. Start a new game.

Result: One frame of animated button texture is corrupted.
